Adding bootstrap to proyect
jshidalgokommit/first-blog pull request #4
Opened 2022-06-16 21:46 UTC by jshidalgokommit

bootstrap implemented in the blog project

2022-06-20 19:23 UTC, JoseCastroA requested changes

2022-06-20 19:23 UTC, JoseCastroA commented on app/controllers/comments_controller.rb
> +  # http_basic_authenticate_with name: 'admin', password: 'admin', only: :destroy
@jshidalgokommit Do we need this comment?

2022-06-20 19:23 UTC, JoseCastroA commented on app/views/articles/edit.html.erb
>  <%= render "form", article: @article %>
@jshidalgokommit Please add an empty line

2022-06-20 19:23 UTC, JoseCastroA commented on app/views/articles/index.html.erb
> +      <a href="<%= article_path article %>" class="list-group-item list-group-item-action" aria-current="true">
@jshidalgokommit Please use link_to instead of href

2022-06-20 19:23 UTC, JoseCastroA commented on app/views/articles/new.html.erb
>  <%= render "form", article: @article %>
@jshidalgokommit Please add an empty line

2022-06-20 19:23 UTC, JoseCastroA commented on app/views/articles/show.html.erb
> +  <% if !@article.comments.empty? %>
@article.comments.present?

2022-06-20 19:23 UTC, JoseCastroA commented on app/views/layouts/application.html.erb
> +        <a type="button" class="btn btn-success" href="<%= new_article_path %>">New post</a>
link_to

2022-06-20 21:51 UTC, jshidalgokommit commented
Hello @JoseCastroA, changes requests have been implemented

2022-06-21 12:18 UTC, JoseCastroA approved these changes

2022-06-21 15:19 UTC, merged