User authentication feature
jshidalgokommit/first-blog pull request #5
Opened 2022-06-20 17:04 UTC by jshidalgokommit

features implemented: 

a. Log in and log out. 

b. Create, edit, delete my blog posts.

c. Add comments in other blog posts only for logged users.

2022-06-21 15:18 UTC, jshidalgokommit commented
Hi @JoseCastroA, the new authentication structure was implemented. Now table Users store auth information and user data (name, last name)

2022-06-22 02:19 UTC, JoseCastroA requested changes

2022-06-22 02:19 UTC, JoseCastroA commented on app/assets/javascripts/devise/registrations/edit.js
> +
@jshidalgokommit Please remove this file

2022-06-22 02:19 UTC, JoseCastroA commented on app/controllers/articles_controller.rb
> +    @article
@jshidalgokommit If you do` @article = Article.find(params[:id])` on the `verify_owner` function, you don't need this line

2022-06-22 02:19 UTC, JoseCastroA commented on app/models/comment.rb
> +  validates :commenter, :body, :user_id, presence: true
Do we need to validate the presence of `article_id`? @jshidalgokommit

2022-06-22 13:49 UTC, jshidalgokommit commented
Hi @JoseCastroA, the requested changes were implemented

2022-06-22 16:09 UTC, JoseCastroA approved these changes

2022-06-22 16:31 UTC, merged